FROM node:10 AS ui-build
WORKDIR /usr/src/app
COPY voguelFront/ ./voguelFront/
RUN cd voguelFront && npm install @angular/cli && npm install && npm run build

FROM node:10 AS server-build
WORKDIR /root/
COPY --from=ui-build /usr/src/app/voguelFront/dist/voguel-banking ./my-app/dist
COPY package*.json ./
RUN npm install
COPY server.js .

EXPOSE 3080

CMD ["yarn", "dev"]